const EQUIPMENT_DATA = {
  categories: [
    {id:'cam', name:'카메라/렌즈', icon:'camera', color:'#1f6feb'},
    {id:'light', name:'조명/스탠드', icon:'sun', color:'#d29922'},
    {id:'audio', name:'음향/마이크', icon:'mic', color:'#3fb950'},
    {id:'broadcast', name:'중계/스위처', icon:'monitor', color:'#bc8cff'},
    {id:'wireless', name:'무선/트랜스미터', icon:'wifi', color:'#f85149'},
    {id:'display', name:'모니터/디스플레이', icon:'tv', color:'#39d353'},
    {id:'support', name:'지지대/드론', icon:'aperture', color:'#ffa657'}
  ],
  subcategories: [
    {id:'cam-cinema', categoryId:'cam', name:'시네마 카메라'},
    {id:'cam-broadcast', categoryId:'cam', name:'방송용 카메라'},
    {id:'cam-ptz', categoryId:'cam', name:'PTZ 카메라'},
    {id:'cam-mirrorless', categoryId:'cam', name:'미러리스/DSLR'},
    {id:'cam-lens', categoryId:'cam', name:'렌즈'},
    {id:'cam-acc', categoryId:'cam', name:'카메라 액세서리'},
    {id:'light-led', categoryId:'light', name:'LED 패널/비디오라이트'},
    {id:'light-hmi', categoryId:'light', name:'HMI/텅스텐'},
    {id:'light-stand', categoryId:'light', name:'스탠드/C스탠드'},
    {id:'light-mod', categoryId:'light', name:'디퓨저/반사판'},
    {id:'light-power', categoryId:'light', name:'전력/배터리'},
    {id:'audio-wireless', categoryId:'audio', name:'무선 마이크 시스템'},
    {id:'audio-boom', categoryId:'audio', name:'붐 마이크'},
    {id:'audio-lav', categoryId:'audio', name:'라발리에 마이크'},
    {id:'audio-mixer', categoryId:'audio', name:'믹서/레코더'},
    {id:'audio-iem', categoryId:'audio', name:'IEM/인이어'},
    {id:'audio-pa', categoryId:'audio', name:'스피커/PA'},
    {id:'bc-switcher', categoryId:'broadcast', name:'비디오 스위처'},
    {id:'bc-encoder', categoryId:'broadcast', name:'인코더/디코더'},
    {id:'bc-router', categoryId:'broadcast', name:'라우터/멀티뷰어'},
    {id:'bc-ccu', categoryId:'broadcast', name:'CCU/카메라 컨트롤'},
    {id:'bc-convert', categoryId:'broadcast', name:'영상 변환기'},
    {id:'wl-video', categoryId:'wireless', name:'무선 영상 송수신'},
    {id:'wl-ifb', categoryId:'wireless', name:'IFB 시스템'},
    {id:'wl-intercom', categoryId:'wireless', name:'인터컴'},
    {id:'wl-tally', categoryId:'wireless', name:'탈리 시스템'},
    {id:'disp-field', categoryId:'display', name:'필드 모니터'},
    {id:'disp-master', categoryId:'display', name:'방송용 마스터 모니터'},
    {id:'disp-led', categoryId:'display', name:'LED 월/전광판'},
    {id:'disp-conf', categoryId:'display', name:'컨피던스 모니터'},
    {id:'sup-tripod', categoryId:'support', name:'삼각대/유체헤드'},
    {id:'sup-crane', categoryId:'support', name:'지브/크레인'},
    {id:'sup-dolly', categoryId:'support', name:'달리/레일'},
    {id:'sup-slider', categoryId:'support', name:'슬라이더'},
    {id:'sup-drone', categoryId:'support', name:'드론'},
    {id:'sup-gimbal', categoryId:'support', name:'짐벌/스태비라이저'}
  ],
  items: [
    {id:'CAM-001',categoryId:'cam',subcategoryId:'cam-cinema',name:'ARRI ALEXA 35',brand:'ARRI',specs:'4K+ Open Gate, LF Sensor, Built-in ND 0.6/1.2/1.8/2.4, LogC3/LogC4, ARRIRAW',dailyRate:850000,status:'available',quantity:2},
    {id:'CAM-002',categoryId:'cam',subcategoryId:'cam-cinema',name:'RED KOMODO-X 6K',brand:'RED',specs:'6K S35, Global Shutter, 40fps 6K, REDCODE RAW, CFexpress Type-B',dailyRate:550000,status:'rented',quantity:2},
    {id:'CAM-003',categoryId:'cam',subcategoryId:'cam-cinema',name:'Sony VENICE 2 8K',brand:'Sony',specs:'8.6K Full Frame 36x24mm, Dual Base ISO 800/3200, Built-in 8-Stop ND, X-OCN/ProRes',dailyRate:780000,status:'available',quantity:1},
    {id:'CAM-004',categoryId:'cam',subcategoryId:'cam-cinema',name:'Blackmagic URSA Mini Pro 12K',brand:'Blackmagic',specs:'12K 80fps, Super 35 Sensor, BRAW, Dual CFast+SD, Built-in ND',dailyRate:280000,status:'available',quantity:3},
    {id:'CAM-005',categoryId:'cam',subcategoryId:'cam-cinema',name:'DJI Ronin 4D 8K Combo',brand:'DJI',specs:'Full Frame 8K, LiDAR Autofocus, 4-Axis Stabilization, 6K 75fps, 13-Stop DR',dailyRate:650000,status:'maintenance',quantity:1},
    {id:'CAM-006',categoryId:'cam',subcategoryId:'cam-cinema',name:'Canon EOS C700 FF Cinema',brand:'Canon',specs:'5.9K Full Frame, Cinema RAW Light, 120fps 2K, PL/EF Mount, Built-in ND',dailyRate:480000,status:'available',quantity:1},
    {id:'CAM-007',categoryId:'cam',subcategoryId:'cam-broadcast',name:'Sony PXW-Z750 4K',brand:'Sony',specs:'4K HDR, 3-CMOS 2/3" 1ch, SxS+SD Dual Slot, HLG/S-Log3, 12G-SDI',dailyRate:220000,status:'available',quantity:4},
    {id:'CAM-008',categoryId:'cam',subcategoryId:'cam-broadcast',name:'Panasonic AU-EVA1 5.7K',brand:'Panasonic',specs:'5.7K Super 35, Dual ND 2/4/6/8-Stop, V-Log, EF Mount, 10-bit 4:2:2',dailyRate:180000,status:'available',quantity:3},
    {id:'CAM-009',categoryId:'cam',subcategoryId:'cam-broadcast',name:'Canon EOS C500 Mark II',brand:'Canon',specs:'6K Full Frame, Cinema RAW Light, 15-Stop DR, EF/PL Mount, Dual Pixel AF',dailyRate:320000,status:'rented',quantity:2},
    {id:'CAM-010',categoryId:'cam',subcategoryId:'cam-broadcast',name:'Panasonic AG-CX350 4K',brand:'Panasonic',specs:'4K 60p, 3MOS 1/3" 3ch, SRT Live Streaming, ND Filter, V-Log L',dailyRate:130000,status:'available',quantity:3},
    {id:'CAM-011',categoryId:'cam',subcategoryId:'cam-ptz',name:'Sony BRC-H900 PTZ',brand:'Sony',specs:'1080p 60fps, 30x Optical Zoom, IP Control, VISCA, RS-422, NDI Optional',dailyRate:120000,status:'available',quantity:6},
    {id:'CAM-012',categoryId:'cam',subcategoryId:'cam-ptz',name:'Panasonic AW-UE100 4K PTZ',brand:'Panasonic',specs:'4K 60p, 20x Zoom, IP/SDI/HDMI Out, NDI|HX, AI Tracking, PoE+',dailyRate:150000,status:'available',quantity:4},
    {id:'CAM-013',categoryId:'cam',subcategoryId:'cam-ptz',name:'Marshall CV612HT-4K PTZ',brand:'Marshall',specs:'4K 60fps, 12x Optical Zoom, PoE+ Powered, HDMI+IP Out, VISCA RS-232',dailyRate:95000,status:'rented',quantity:2},
    {id:'CAM-014',categoryId:'cam',subcategoryId:'cam-ptz',name:'Sony SRG-A40 4K AI PTZ',brand:'Sony',specs:'4K 60p, 40x Zoom, AI Auto-Framing, NDI|HX3, SRT, PoE++',dailyRate:180000,status:'available',quantity:2},
    {id:'CAM-015',categoryId:'cam',subcategoryId:'cam-mirrorless',name:'Sony A7S III',brand:'Sony',specs:'12.1MP Full Frame, ISO 80-102400, 4K 120fps 10-bit, S-Log3, CFexpress A',dailyRate:95000,status:'available',quantity:5},
    {id:'CAM-016',categoryId:'cam',subcategoryId:'cam-mirrorless',name:'Canon EOS R5C',brand:'Canon',specs:'8K RAW Internal, Full Frame 45MP, Unlimited 4K Recording, Cinema EOS Color',dailyRate:130000,status:'available',quantity:3},
    {id:'CAM-017',categoryId:'cam',subcategoryId:'cam-mirrorless',name:'Nikon Z9',brand:'Nikon',specs:'45.7MP Stacked CMOS, 8K 60p RAW, 120fps 4K, N-Log, ProRes RAW',dailyRate:120000,status:'rented',quantity:2},
    {id:'CAM-018',categoryId:'cam',subcategoryId:'cam-mirrorless',name:'Sony FX3 Full Frame Cinema',brand:'Sony',specs:'12.1MP Full Frame, 4K 120fps, Dual Base ISO, S-Cinetone, Active Cooling',dailyRate:85000,status:'available',quantity:4},
    {id:'CAM-019',categoryId:'cam',subcategoryId:'cam-mirrorless',name:'Panasonic S5 IIX',brand:'Panasonic',specs:'24.2MP Full Frame, 4K 120fps, ProRes Recording via SSD, L-Mount, 14-Stop DR',dailyRate:75000,status:'available',quantity:3},
    {id:'CAM-020',categoryId:'cam',subcategoryId:'cam-lens',name:'ZEISS Supreme Prime 25mm T1.5',brand:'ZEISS',specs:'25mm T1.5 Full Frame, PL/LPL/EF Mount, /i Technology, 95mm Front',dailyRate:180000,status:'available',quantity:2},
    {id:'CAM-021',categoryId:'cam',subcategoryId:'cam-lens',name:'Cooke S7/i Anamorphic 40mm 2x',brand:'Cooke',specs:'40mm 2x Anamorphic, Full Frame+, /i Technology, Oval Bokeh, PL Mount',dailyRate:220000,status:'available',quantity:1},
    {id:'CAM-022',categoryId:'cam',subcategoryId:'cam-lens',name:'Fujinon XA20sx8.5BRM 방송 박스렌즈',brand:'Fujinon',specs:'20x Zoom 8.5-170mm, 4K, Servo, 2/3" Broadcast, B4 Mount',dailyRate:95000,status:'available',quantity:3},
    {id:'CAM-023',categoryId:'cam',subcategoryId:'cam-lens',name:'Canon CN-E 15-135mm T2.4 L SP',brand:'Canon',specs:'Cinema EOS 15-135mm T2.4 Parfocal Zoom, PL/EF Mount, 4K Optimized',dailyRate:120000,status:'rented',quantity:1},
    {id:'CAM-024',categoryId:'cam',subcategoryId:'cam-lens',name:'Sigma Cine 18-35mm T2 고속줌',brand:'Sigma',specs:'18-35mm T2.0 High Speed Zoom, PL/EF/E Mount, 114mm Front, Parfocal',dailyRate:85000,status:'available',quantity:2},
    {id:'CAM-025',categoryId:'cam',subcategoryId:'cam-lens',name:'ARRI/Zeiss Master Prime 50mm T1.3',brand:'ARRI/Zeiss',specs:'50mm T1.3, Super 35, PL Mount, /i Technology, Ultra-Low Distortion',dailyRate:200000,status:'available',quantity:1},
    {id:'CAM-026',categoryId:'cam',subcategoryId:'cam-acc',name:'SmallRig 카메라 케이지 A7S III',brand:'SmallRig',specs:'Sony A7S III Cage Kit, ARRI Locating, NATO Rail, Cold Shoe x4',dailyRate:25000,status:'available',quantity:5},
    {id:'CAM-027',categoryId:'cam',subcategoryId:'cam-acc',name:'Preston HU4 핸드유닛 + FI+Z-3',brand:'Preston',specs:'Hand Unit 4, FI+Z-3 Focus/Iris/Zoom Control, Wireless, 2.4GHz',dailyRate:180000,status:'available',quantity:2},
    {id:'CAM-028',categoryId:'cam',subcategoryId:'cam-acc',name:'ARRI MB-20 매트박스',brand:'ARRI',specs:'4x5.65 Matte Box, Swing-Away, 2-Stage Filter, 138mm Rear',dailyRate:35000,status:'available',quantity:4},
    {id:'CAM-029',categoryId:'cam',subcategoryId:'cam-acc',name:'Chrosziel 4x4 Follow Focus',brand:'Chrosziel',specs:'FU-1 Follow Focus Universal, Quick Release, 15/19mm Rail',dailyRate:20000,status:'available',quantity:6},
    {id:'CAM-030',categoryId:'cam',subcategoryId:'cam-acc',name:'Wooden Camera Director\'s Monitor Cage',brand:'Wooden Camera',specs:'Universal Monitor Cage, Cold Shoe, ARRI Rosette, 15mm LW Rod',dailyRate:15000,status:'available',quantity:6},

    {id:'LIGHT-001',categoryId:'light',subcategoryId:'light-led',name:'ARRI SkyPanel S360-C RGBWW',brand:'ARRI',specs:'360W RGBWW LED Soft, 1x1 Panel, DMX/RDM, Ethernet, Bluetooth, Bowens',dailyRate:280000,status:'available',quantity:2},
    {id:'LIGHT-002',categoryId:'light',subcategoryId:'light-led',name:'Aputure LS 600d Pro Daylight',brand:'Aputure',specs:'600W 5600K Daylight, Bowens S-Mount, Sidus Link App, IP54, V-Mount',dailyRate:120000,status:'available',quantity:4},
    {id:'LIGHT-003',categoryId:'light',subcategoryId:'light-led',name:'Litepanels Gemini 2x1 RGBWW',brand:'Litepanels',specs:'2x1 Soft Panel, Full RGBWW, 2000+ Kelvin Range, IP54, DMX/Bluetooth',dailyRate:130000,status:'rented',quantity:3},
    {id:'LIGHT-004',categoryId:'light',subcategoryId:'light-led',name:'Nanlux Evoke 1200 Spot LED',brand:'Nanlux',specs:'1200W 5600K, Fresnel+Reflector, Bowens, Wireless Dimming, CRI 96+',dailyRate:95000,status:'available',quantity:4},
    {id:'LIGHT-005',categoryId:'light',subcategoryId:'light-led',name:'Rotolight Titan X2 RGBWW',brand:'Rotolight',specs:'High Speed Sync 1/8000s, Chromagreen FX, 3000-10000K, NexGen LED',dailyRate:85000,status:'available',quantity:3},
    {id:'LIGHT-006',categoryId:'light',subcategoryId:'light-led',name:'Godox SL300III Bi-Color LED',brand:'Godox',specs:'300W 2800-6500K Bi-Color, Bowens, Godox Light App, 96+ CRI, Fan/Fanless',dailyRate:55000,status:'available',quantity:6},
    {id:'LIGHT-007',categoryId:'light',subcategoryId:'light-led',name:'ARRI SkyPanel S60-C RGBWW',brand:'ARRI',specs:'195W RGBWW Softlight, DMX/RDM, LumenRadio CRMX, USB-C, Ethernet',dailyRate:120000,status:'available',quantity:4},
    {id:'LIGHT-008',categoryId:'light',subcategoryId:'light-led',name:'Kino Flo Diva-Lite 31 LED',brand:'Kino Flo',specs:'3ft Diva-Lite, Tungsten/Daylight/FX Modes, Flicker-Free, DMX',dailyRate:65000,status:'available',quantity:4},
    {id:'LIGHT-009',categoryId:'light',subcategoryId:'light-hmi',name:'ARRI M18 1800W HMI',brand:'ARRI',specs:'1800W HMI, EB MAX Electronic Ballast, 5600K, Fresnel, IP44',dailyRate:180000,status:'available',quantity:2},
    {id:'LIGHT-010',categoryId:'light',subcategoryId:'light-hmi',name:'K5600 Joker-Bug 800 HMI',brand:'K5600',specs:'800W HMI, Pocket Par Head, Daylight 5600K, MSR 800/2 Lamp',dailyRate:120000,status:'rented',quantity:2},
    {id:'LIGHT-011',categoryId:'light',subcategoryId:'light-hmi',name:'Arri Compact 200 HMI',brand:'ARRI',specs:'200W HMI, 5600K, Fresnel 6.5", EB, Flicker-Free 50/60Hz',dailyRate:75000,status:'available',quantity:3},
    {id:'LIGHT-012',categoryId:'light',subcategoryId:'light-stand',name:'Matthews 100cm 크롬 C스탠드',brand:'Matthews',specs:'40" C-Stand Chrome, Sliding Leg, 3-Section Riser, 3/8" Spigot',dailyRate:15000,status:'available',quantity:20},
    {id:'LIGHT-013',categoryId:'light',subcategoryId:'light-stand',name:'Avenger 대형 붐 암 스탠드 세트',brand:'Avenger',specs:'A2035B Boom + A100 Baby Stand, 10kg Load, 120cm Arm',dailyRate:25000,status:'available',quantity:10},
    {id:'LIGHT-014',categoryId:'light',subcategoryId:'light-stand',name:'Manfrotto 5001B 나노 스탠드',brand:'Manfrotto',specs:'Nano Stand, 1.9m Max, 3kg, Black Anodized Aluminum, Compact Folding',dailyRate:8000,status:'available',quantity:15},
    {id:'LIGHT-015',categoryId:'light',subcategoryId:'light-mod',name:'Rosco 4x4 젤 필터 세트',brand:'Rosco',specs:'CTO/CTB/1/2CTO/Diffusion/ND 4x4 Gel Roll Set, 25-Sheet Pack',dailyRate:15000,status:'available',quantity:8},
    {id:'LIGHT-016',categoryId:'light',subcategoryId:'light-mod',name:'Chimera 4x6 소프트박스',brand:'Chimera',specs:'4x6 Large Softbox, Speed Ring, Inner/Outer Baffle, Egg Crate Optional',dailyRate:35000,status:'available',quantity:4},
    {id:'LIGHT-017',categoryId:'light',subcategoryId:'light-mod',name:'Photoflex 42" 은면/금면 반사판',brand:'Photoflex',specs:'42" 5-in-1 Reflector, Silver/Gold/White/Black/Translucent, Collapsible',dailyRate:10000,status:'available',quantity:10},
    {id:'LIGHT-018',categoryId:'light',subcategoryId:'light-power',name:'Anton Bauer 파워디스트리뷰션 박스',brand:'Anton Bauer',specs:'8-Channel 12V/24V Power Distribution, 30A Per Channel, XLR-4',dailyRate:45000,status:'available',quantity:4},
    {id:'LIGHT-019',categoryId:'light',subcategoryId:'light-power',name:'Cineroid LB4200C V마운트 배터리',brand:'Cineroid',specs:'V-Mount 150Wh, 14.4V, D-Tap x2, USB, Level Indicator, 1050g',dailyRate:15000,status:'available',quantity:12},
    {id:'LIGHT-020',categoryId:'light',subcategoryId:'light-power',name:'Core SWX Fleet Micro V마운트 충전기',brand:'Core SWX',specs:'4-Bay V-Mount Charger, 4A Per Bay, LED Status, DC Out, 1RU',dailyRate:20000,status:'available',quantity:3},

    {id:'AUDIO-001',categoryId:'audio',subcategoryId:'audio-wireless',name:'Sennheiser EW 6000 멀티채널 무선',brand:'Sennheiser',specs:'UHF Wireless System, 12-Channel Simultaneous, 250m Range, Dante Output',dailyRate:95000,status:'available',quantity:6},
    {id:'AUDIO-002',categoryId:'audio',subcategoryId:'audio-wireless',name:'Lectrosonics SSM 슈퍼슬림 무선',brand:'Lectrosonics',specs:'Servo Bias Transmitter, 250mW, Frequency Agile, 470-614MHz, SMQV Compatible',dailyRate:120000,status:'rented',quantity:4},
    {id:'AUDIO-003',categoryId:'audio',subcategoryId:'audio-wireless',name:'Sony UWP-D Series 무선 마이크',brand:'Sony',specs:'UHF Wireless, Shoe-Mount Receiver, XLR Bodypack, 574-698MHz, Squelch',dailyRate:55000,status:'available',quantity:8},
    {id:'AUDIO-004',categoryId:'audio',subcategoryId:'audio-wireless',name:'Shure Axient AD Series 디지털',brand:'Shure',specs:'Digital Wireless, AES-256, Dante/AES67, 1000ft Range, Frequency Diversity',dailyRate:140000,status:'available',quantity:4},
    {id:'AUDIO-005',categoryId:'audio',subcategoryId:'audio-wireless',name:'Wisycom MCR54 쿼드 수신기',brand:'Wisycom',specs:'Quad Receiver, UHF 470-960MHz, Dante, AES3, True Diversity, 1RU',dailyRate:130000,status:'available',quantity:2},
    {id:'AUDIO-006',categoryId:'audio',subcategoryId:'audio-boom',name:'Sennheiser MKH 416 P48 샷건',brand:'Sennheiser',specs:'Interference Tube Shotgun, P48, 40-20kHz, 200ohm, Short Shotgun Design',dailyRate:35000,status:'available',quantity:6},
    {id:'AUDIO-007',categoryId:'audio',subcategoryId:'audio-boom',name:'Rode NTG5 초지향성 RF바이어스',brand:'Rode',specs:'Supercardioid Shotgun, RF-Bias, 19.5g, 200Hz-20kHz, MZL Connector',dailyRate:25000,status:'available',quantity:5},
    {id:'AUDIO-008',categoryId:'audio',subcategoryId:'audio-boom',name:'Sennheiser MKH 50 P48 스튜디오',brand:'Sennheiser',specs:'Supercardioid, P48, 40Hz-20kHz, Extremely Low Self Noise 10dB-A, RF',dailyRate:30000,status:'available',quantity:4},
    {id:'AUDIO-009',categoryId:'audio',subcategoryId:'audio-boom',name:'Audio-Technica BP4073 Line+Gradient',brand:'Audio-Technica',specs:'Line+Gradient Shotgun, 30Hz-20kHz, P12-48, 150ohm, Low Profile',dailyRate:20000,status:'available',quantity:4},
    {id:'AUDIO-010',categoryId:'audio',subcategoryId:'audio-lav',name:'Sanken COS-11D 라발리에 마이크',brand:'Sanken',specs:'Omni Lavalier, 40-20kHz, Pigtail Connector, Waterproof, 2.5mm diameter',dailyRate:20000,status:'available',quantity:10},
    {id:'AUDIO-011',categoryId:'audio',subcategoryId:'audio-lav',name:'DPA 4060-B 미니어처 라발리에',brand:'DPA',specs:'Omni, 20Hz-20kHz, MicroDot, 2Vrms, 3mm Capsule, Low/High Sensitivity',dailyRate:25000,status:'rented',quantity:6},
    {id:'AUDIO-012',categoryId:'audio',subcategoryId:'audio-lav',name:'Countryman B6 초소형 라발리에',brand:'Countryman',specs:'Omni 2.5mm, 100Hz-20kHz, P48, 1500ohm, Water/Sweat Resistant',dailyRate:18000,status:'available',quantity:8},
    {id:'AUDIO-013',categoryId:'audio',subcategoryId:'audio-mixer',name:'Sound Devices 888 포터블 믹서',brand:'Sound Devices',specs:'8-Track Recorder/Mixer, 32-bit Float, Dante, CL-12 Control, 5pin Hirose',dailyRate:180000,status:'available',quantity:2},
    {id:'AUDIO-014',categoryId:'audio',subcategoryId:'audio-mixer',name:'Zoom F8n Pro 필드 레코더',brand:'Zoom',specs:'8-Input, 32-bit Float, Timecode, USB-C Audio, 10-Track, SD/SDHC',dailyRate:65000,status:'available',quantity:4},
    {id:'AUDIO-015',categoryId:'audio',subcategoryId:'audio-mixer',name:'Yamaha CL5 디지털 라이브 콘솔',brand:'Yamaha',specs:'72 Inputs, 24 Mix, 8 Matrix, Dante, CL Editor, Digital I/O Expansion',dailyRate:280000,status:'available',quantity:1},
    {id:'AUDIO-016',categoryId:'audio',subcategoryId:'audio-mixer',name:'Allen & Heath dLive CDM32',brand:'Allen & Heath',specs:'32-Channel Surface, 128 Inputs, DM0 Mix Rack, MADI, Dante, 96kHz',dailyRate:320000,status:'rented',quantity:1},
    {id:'AUDIO-017',categoryId:'audio',subcategoryId:'audio-iem',name:'Shure PSM 900 인이어 모니터 시스템',brand:'Shure',specs:'IEM System, 10mW, True Diversity Stereo, 300m Range, G7E Band',dailyRate:85000,status:'available',quantity:4},
    {id:'AUDIO-018',categoryId:'audio',subcategoryId:'audio-iem',name:'Sennheiser 2000 Series IEM',brand:'Sennheiser',specs:'In-Ear Monitoring, 2050 Transmitter, 2000 Bodypack, Stereo Pilot Tone',dailyRate:75000,status:'available',quantity:4},
    {id:'AUDIO-019',categoryId:'audio',subcategoryId:'audio-pa',name:'QSC K12.2 액티브 스피커',brand:'QSC',specs:'2000W Class D, 12" Woofer, 75Hz-20kHz, DMT, QSC Deep Mode DSP',dailyRate:75000,status:'available',quantity:4},
    {id:'AUDIO-020',categoryId:'audio',subcategoryId:'audio-pa',name:'Yamaha DZR315 3웨이 스피커',brand:'Yamaha',specs:'2000W 3-Way, 15"/3"/1", Dante Network, DSP, FIR-X Tuning',dailyRate:95000,status:'available',quantity:4},
    {id:'AUDIO-021',categoryId:'audio',subcategoryId:'audio-pa',name:'QSC KS212C 카디오이드 서브우퍼',brand:'QSC',specs:'3600W Cardioid Subwoofer, Dual 12", 37Hz-100Hz, Deep, Standard Modes',dailyRate:80000,status:'available',quantity:2},
    {id:'AUDIO-022',categoryId:'audio',subcategoryId:'audio-pa',name:'Yamaha DM7 디지털 믹싱 콘솔',brand:'Yamaha',specs:'144 Input, Dante, 5.1 Surround Mix, ProVisionaire Control, SILK Processing',dailyRate:320000,status:'rented',quantity:1},

    {id:'BC-001',categoryId:'broadcast',subcategoryId:'bc-switcher',name:'Blackmagic ATEM 4 M/E 방송 스튜디오',brand:'Blackmagic',specs:'4 M/E, 40 Inputs, DVE, SuperSource, HyperDeck, Streaming Output',dailyRate:280000,status:'available',quantity:2},
    {id:'BC-002',categoryId:'broadcast',subcategoryId:'bc-switcher',name:'Blackmagic ATEM Mini Extreme ISO',brand:'Blackmagic',specs:'8-Input, Full ISO Record, 4K Output, ATEM Software Control, USB-C',dailyRate:65000,status:'available',quantity:4},
    {id:'BC-003',categoryId:'broadcast',subcategoryId:'bc-switcher',name:'Ross Video Carbonite Ultra',brand:'Ross Video',specs:'6 M/E, 96 Inputs, 4K UHD, Built-in Multiviewer, XPression CG Integration',dailyRate:550000,status:'available',quantity:1},
    {id:'BC-004',categoryId:'broadcast',subcategoryId:'bc-switcher',name:'Sony XVS-G1 4K 라이브 스위처',brand:'Sony',specs:'2 M/E, 24 Inputs, 4K/HD, IP Live, Instant Replay, MXF/XAVC',dailyRate:380000,status:'available',quantity:1},
    {id:'BC-005',categoryId:'broadcast',subcategoryId:'bc-switcher',name:'Panasonic AV-UHS500 라이브 스위처',brand:'Panasonic',specs:'4K 2 M/E, 20 Inputs, 3G/12G-SDI, IP-NMI, AV-UHS500 Series',dailyRate:250000,status:'rented',quantity:1},
    {id:'BC-006',categoryId:'broadcast',subcategoryId:'bc-encoder',name:'Teradek CUBE 655 4K 인코더',brand:'Teradek',specs:'4K HEVC/H.264 Encoder, SRT, NDI, 12G-SDI, Dante, RTMP/RTSP',dailyRate:95000,status:'rented',quantity:3},
    {id:'BC-007',categoryId:'broadcast',subcategoryId:'bc-encoder',name:'Haivision Makito X 인코더 1RU',brand:'Haivision',specs:'HD H.264/HEVC Encoder, SRT, RTMP, TS over IP, Dante, 1RU Rackmount',dailyRate:120000,status:'available',quantity:2},
    {id:'BC-008',categoryId:'broadcast',subcategoryId:'bc-encoder',name:'Blackmagic Web Presenter 4K',brand:'Blackmagic',specs:'4K Streaming, Teaming for Bonding, SRT, USB Webcam Output, SDI+HDMI',dailyRate:45000,status:'available',quantity:4},
    {id:'BC-009',categoryId:'broadcast',subcategoryId:'bc-router',name:'Blackmagic Videohub 72x72 12G',brand:'Blackmagic',specs:'72x72 12G-SDI Router, Smart Videohub Control, Redundant PSU, 4RU',dailyRate:180000,status:'available',quantity:1},
    {id:'BC-010',categoryId:'broadcast',subcategoryId:'bc-router',name:'Blackmagic MultiView 16 HD/4K',brand:'Blackmagic',specs:'16-Input Multiviewer, HD/4K Output, Smart Tally, SDI/HDMI Out',dailyRate:85000,status:'available',quantity:2},
    {id:'BC-011',categoryId:'broadcast',subcategoryId:'bc-ccu',name:'Sony HDCU-3500 4K CCU',brand:'Sony',specs:'4K/HDR Camera Control Unit, IP/Fiber, for HDC-4300/3500 Series',dailyRate:220000,status:'rented',quantity:2},
    {id:'BC-012',categoryId:'broadcast',subcategoryId:'bc-ccu',name:'Grass Valley LDX 86N CCU 시스템',brand:'Grass Valley',specs:'4K/HDR MultiFormat CCU, 2x3G/12G-SDI, IP, PoF, for LDX Series',dailyRate:280000,status:'available',quantity:1},
    {id:'BC-013',categoryId:'broadcast',subcategoryId:'bc-convert',name:'AJA FS-HDR 4K 프레임 싱크/컨버터',brand:'AJA',specs:'4K/2K/HD Frame Sync, HDR Conversion, 12G-SDI, 1RU, HLG/PQ Support',dailyRate:65000,status:'available',quantity:4},
    {id:'BC-014',categoryId:'broadcast',subcategoryId:'bc-convert',name:'Blackmagic Mini Converter 12G SDI-HDMI',brand:'Blackmagic',specs:'12G-SDI to HDMI 2.0 Converter, 4K Ultra HD, 60fps, Metadata',dailyRate:15000,status:'available',quantity:8},
    {id:'BC-015',categoryId:'broadcast',subcategoryId:'bc-convert',name:'AJA D4 HDR 다운컨버터',brand:'AJA',specs:'4K to HD Down Conversion, HDR to SDR, 12G/6G/3G-SDI, 1RU',dailyRate:45000,status:'available',quantity:3},

    {id:'WL-001',categoryId:'wireless',subcategoryId:'wl-video',name:'Teradek Bolt 6 XT 4K 무선영상',brand:'Teradek',specs:'4K 12G Wireless, 300m LOS, Zero-Delay <1ms, 6 RX Expandable',dailyRate:180000,status:'available',quantity:4},
    {id:'WL-002',categoryId:'wireless',subcategoryId:'wl-video',name:'Hollyland Mars 4K LT 무선송수신',brand:'Hollyland',specs:'4K HDMI Wireless, 120m Range, 0.08s Latency, Dual RX Out',dailyRate:65000,status:'available',quantity:6},
    {id:'WL-003',categoryId:'wireless',subcategoryId:'wl-video',name:'DJI Transmission 4K 무선 영상',brand:'DJI',specs:'4K@60fps Wireless, 600m Range, 3-Receiver Support, USB-C Power',dailyRate:85000,status:'rented',quantity:3},
    {id:'WL-004',categoryId:'wireless',subcategoryId:'wl-video',name:'Paralinx Arrow-X 1:2 무선영상',brand:'Paralinx',specs:'1:2 TX+2RX, 1080p 60fps, 300ft, <1ms, SDI+HDMI Loop',dailyRate:95000,status:'available',quantity:2},
    {id:'WL-005',categoryId:'wireless',subcategoryId:'wl-ifb',name:'Lectrosonics IFBT4 IFB 시스템',brand:'Lectrosonics',specs:'IFB Transmitter, AM+FM, 100mW, 470-614MHz, XLR Input, Antenna Split',dailyRate:65000,status:'available',quantity:4},
    {id:'WL-006',categoryId:'wireless',subcategoryId:'wl-ifb',name:'Comtek PR-216 IFB 수신기',brand:'Comtek',specs:'IFB Pocket Receiver, 216MHz, Single AA, Belt Clip, Earphone Out',dailyRate:20000,status:'available',quantity:12},
    {id:'WL-007',categoryId:'wireless',subcategoryId:'wl-intercom',name:'Clear-Com FreeSpeak II 디지털 인터컴',brand:'Clear-Com',specs:'DECT 1.9GHz, 4-Channel Full-Duplex, 10-User Beltpack, IP Hub',dailyRate:220000,status:'available',quantity:1},
    {id:'WL-008',categoryId:'wireless',subcategoryId:'wl-intercom',name:'RTS BP325 벨트팩 인터컴',brand:'RTS',specs:'2-Channel Beltpack, A1/A2 Matrix, XLR4 Headset, Belt Clip, MUTE',dailyRate:35000,status:'available',quantity:8},
    {id:'WL-009',categoryId:'wireless',subcategoryId:'wl-intercom',name:'Pliant CrewCom 무선 인터컴 시스템',brand:'Pliant',specs:'UHF DECT, 1.9GHz, 8-User, 4-Channel, 300m Range, Ethernet Sync',dailyRate:180000,status:'available',quantity:1},
    {id:'WL-010',categoryId:'wireless',subcategoryId:'wl-tally',name:'RTS TIF-5000 탈리 인터페이스',brand:'RTS',specs:'32-Port Tally Interface, GPI/GPO, Ethernet Control, Matrix Compatible',dailyRate:65000,status:'available',quantity:2},
    {id:'WL-011',categoryId:'wireless',subcategoryId:'wl-tally',name:'Decimator MD-HX 탈리 미니컨버터',brand:'Decimator',specs:'HDMI+SDI Cross Converter, Tally In/Out, 3G/6G/12G SDI, Scaling',dailyRate:25000,status:'available',quantity:4},
    {id:'WL-012',categoryId:'wireless',subcategoryId:'wl-tally',name:'Blackmagic 3G-SDI Arduino Shield 탈리',brand:'Blackmagic',specs:'3G-SDI Tally Interface, Arduino Compatible, V-Tally/Tally Bus, OPT-ISO',dailyRate:15000,status:'available',quantity:4},

    {id:'DISP-001',categoryId:'display',subcategoryId:'disp-field',name:'SmallHD CINE 7 터치스크린 모니터',brand:'SmallHD',specs:'7" 1920x1200, 2500nit Daylight, 3D LUT, Waveform/Vector, SDI+HDMI',dailyRate:55000,status:'available',quantity:6},
    {id:'DISP-002',categoryId:'display',subcategoryId:'disp-field',name:'Atomos Shogun Ultra 13.3" 레코더',brand:'Atomos',specs:'13.3" 4000nit HDR, ProRes RAW, HDMI 2.1, Apple ProRes 4444, 8K',dailyRate:85000,status:'available',quantity:4},
    {id:'DISP-003',categoryId:'display',subcategoryId:'disp-field',name:'TVLogic LVM-173W 17인치 필드',brand:'TVLogic',specs:'17" 1920x1080, Waveform/Vectorscope, 3G-SDI x4, HDMI, 3D LUT',dailyRate:65000,status:'rented',quantity:3},
    {id:'DISP-004',categoryId:'display',subcategoryId:'disp-field',name:'Convergent Design Odyssey 7Q+',brand:'Convergent Design',specs:'7" RAW Recorder Monitor, SDI/HDMI, Apple ProRes, DNxHD, 4K RAW',dailyRate:70000,status:'available',quantity:3},
    {id:'DISP-005',categoryId:'display',subcategoryId:'disp-master',name:'Sony BVM-HX310 4K HDR 마스터 모니터',brand:'Sony',specs:'31" 4K HDR Master, 1000cd/m2, BT.2020, Dolby Vision, 10/12-bit',dailyRate:350000,status:'available',quantity:1},
    {id:'DISP-006',categoryId:'display',subcategoryId:'disp-master',name:'Flanders Scientific DM240 4K HDR',brand:'Flanders Scientific',specs:'24" 4K, 4000nit, True Black, HDR ST2084, BT.2020, 12G-SDI, HDMI 2.0',dailyRate:180000,status:'available',quantity:2},
    {id:'DISP-007',categoryId:'display',subcategoryId:'disp-master',name:'Canon DP-V2420 참조 모니터 4K',brand:'Canon',specs:'24" 4K HDR, 1000nit, BT.2020, DCI-P3, HDMI/SDI, 12G-SDI',dailyRate:130000,status:'available',quantity:1},
    {id:'DISP-008',categoryId:'display',subcategoryId:'disp-led',name:'ROE Visual Carbon CB5 LED 월 5x3m',brand:'ROE Visual',specs:'5mm Pitch Indoor, 5x3m Panel Set, 1000nit, High Contrast, Power over Fiber',dailyRate:1200000,status:'available',quantity:1},
    {id:'DISP-009',categoryId:'display',subcategoryId:'disp-led',name:'Samsung LED 비전 P2.5 2x2m 세트',brand:'Samsung',specs:'2.5mm Pitch, 2x2m Configuration, 600nit, IP54, Magnesium Die-Cast',dailyRate:450000,status:'rented',quantity:1},
    {id:'DISP-010',categoryId:'display',subcategoryId:'disp-led',name:'Absen Acclaim 3.9 Indoor LED 3x2m',brand:'Absen',specs:'3.9mm Pitch, 3x2m, 800nit, Colorlight 5A Controller, HD Player',dailyRate:380000,status:'available',quantity:1},
    {id:'DISP-011',categoryId:'display',subcategoryId:'disp-conf',name:'LG 55" 4K 컨피던스 모니터 세트',brand:'LG',specs:'55" 4K UHD IPS Commercial, SDI Input Card, HDMI x4, VESA 400x400',dailyRate:75000,status:'available',quantity:4},
    {id:'DISP-012',categoryId:'display',subcategoryId:'disp-conf',name:'Samsung 43" 비즈니스 컨피던스 디스플레이',brand:'Samsung',specs:'43" 4K, 500nit, HDMI x3, DP, RS232/LAN Control, Slim Bezel',dailyRate:45000,status:'available',quantity:6},

    {id:'SUP-001',categoryId:'support',subcategoryId:'sup-tripod',name:'Sachtler aktiv8 유체헤드 + 탄소발 세트',brand:'Sachtler',specs:'8kg Payload, Fluid Head, Carbon Fiber Legs, Touch&Go, 3/8" Flatbase',dailyRate:65000,status:'available',quantity:6},
    {id:'SUP-002',categoryId:'support',subcategoryId:'sup-tripod',name:"O'Connor 2575 Heavy Duty 헤드",brand:"O'Connor",specs:'75mm Ball, 75lb Payload, Touch&Go Pan/Tilt, Claw Ball Leveling',dailyRate:120000,status:'available',quantity:2},
    {id:'SUP-003',categoryId:'support',subcategoryId:'sup-tripod',name:'Miller Arrow 55 알루미늄 시스템',brand:'Miller',specs:'55mm Ball, 11kg Load, Sprinter II 75 Legs, Pan Bar, Ground Spreader',dailyRate:45000,status:'rented',quantity:4},
    {id:'SUP-004',categoryId:'support',subcategoryId:'sup-tripod',name:'Vinten Vision 250 방송헤드 시스템',brand:'Vinten',specs:'250lb Payload, Positive Step Counterbalance, Illuminated Scale, OB/Studio',dailyRate:150000,status:'available',quantity:2},
    {id:'SUP-005',categoryId:'support',subcategoryId:'sup-tripod',name:'Cartoni Lambda 100 알루미늄 시스템',brand:'Cartoni',specs:'100mm Ball, 30kg Load, Adjustable CB, Al Legs, Illuminated Spirit Level',dailyRate:80000,status:'available',quantity:3},
    {id:'SUP-006',categoryId:'support',subcategoryId:'sup-crane',name:'Egripment 4m 원격헤드 지브 크레인',brand:'Egripment',specs:'4m Telescoping Jib, Remote Head Ready, 15kg Payload, Pan/Tilt Motor',dailyRate:280000,status:'available',quantity:1},
    {id:'SUP-007',categoryId:'support',subcategoryId:'sup-crane',name:'Dana Dolly 트랙 달리 크레인 시스템',brand:'Dana Dolly',specs:'Track Dolly, Aluminum Extrusion Track 4ft Set, Pipe Mount, Level Gauge',dailyRate:95000,status:'available',quantity:2},
    {id:'SUP-008',categoryId:'support',subcategoryId:'sup-crane',name:'Libec NEXUS N8 지브 크레인',brand:'Libec',specs:'2.8m Jib Arm, 8kg Payload, Pan/Tilt Remote, Counterweight, Video Head',dailyRate:150000,status:'available',quantity:1},
    {id:'SUP-009',categoryId:'support',subcategoryId:'sup-dolly',name:'Fisher 11 스튜디오 달리',brand:'Fisher',specs:'Studio Dolly, Pneumatic Tires, Crab/Conventional/Circular, 300lb Load',dailyRate:180000,status:'available',quantity:1},
    {id:'SUP-010',categoryId:'support',subcategoryId:'sup-dolly',name:'Elemack Cricket 달리 + 레일 세트',brand:'Elemack',specs:'Cricket Dolly, 4-Wheel Steering, Curved+Straight Track, 100kg Load',dailyRate:130000,status:'available',quantity:1},
    {id:'SUP-011',categoryId:'support',subcategoryId:'sup-slider',name:'Kessler CineSlider 100cm 모터라이즈드',brand:'Kessler',specs:'100cm Travel, Motorized, 11kg Payload, CineShooter Controller, Timelapse',dailyRate:65000,status:'available',quantity:3},
    {id:'SUP-012',categoryId:'support',subcategoryId:'sup-slider',name:'Edelkrone SliderPLUS PRO XL 110cm',brand:'Edelkrone',specs:'110cm Travel, 12kg Load, Intelligent Motion, HELIX+ Compatible, Carbon',dailyRate:55000,status:'rented',quantity:2},
    {id:'SUP-013',categoryId:'support',subcategoryId:'sup-slider',name:'iFootage Shark Slider S1 60cm',brand:'iFootage',specs:'60cm Carbon Slider, 10kg, Fluid Motion, 3/8"+1/4" Mount, Folding Leg',dailyRate:35000,status:'available',quantity:4},
    {id:'SUP-014',categoryId:'support',subcategoryId:'sup-drone',name:'DJI Inspire 3 드론 (조종사 포함)',brand:'DJI',specs:'8K X9-8K Air Gimbal, CineCore 3.0, 45min Flight, Level 7 Wind, CDNG RAW',dailyRate:850000,status:'available',quantity:1},
    {id:'SUP-015',categoryId:'support',subcategoryId:'sup-drone',name:'DJI Matrice 350 RTK 산업용 드론',brand:'DJI',specs:'6kg Payload, 55min Flight, RTK GPS, IP55, O3 Enterprise, Triple Redundancy',dailyRate:650000,status:'available',quantity:1},
    {id:'SUP-016',categoryId:'support',subcategoryId:'sup-drone',name:'Autel Robotics EVO II Pro V3',brand:'Autel',specs:'6K 1" CMOS, 40min Flight, 9km Range, 6K@30fps, Variable Aperture f/2.8-11',dailyRate:350000,status:'available',quantity:1},
    {id:'SUP-017',categoryId:'support',subcategoryId:'sup-gimbal',name:'DJI RS 4 Pro 3축 짐벌 스태비라이저',brand:'DJI',specs:'3kg Payload, OLED Display, BT Focus Motor, PD Charging, LiDAR Focus',dailyRate:45000,status:'available',quantity:5},
    {id:'SUP-018',categoryId:'support',subcategoryId:'sup-gimbal',name:'Zhiyun CRANE 4 짐벌',brand:'Zhiyun',specs:'3.5kg Payload, SuperSmooth 3.0, Vertical/Horizontal, PD Fast Charge, ViaTouch',dailyRate:35000,status:'available',quantity:4},
    {id:'SUP-019',categoryId:'support',subcategoryId:'sup-gimbal',name:'Tilta Gravity G2X 짐벌 시스템',brand:'Tilta',specs:'4.5kg Payload, Quick Release, Follow Focus Built-in, 12hr Runtime, 3-Axis',dailyRate:55000,status:'available',quantity:2},
    {id:'SUP-020',categoryId:'support',subcategoryId:'sup-gimbal',name:'Movi Pro 3축 자이로 스태비라이저',brand:'Freefly',specs:'4.5kg Payload, MIMIC Motion Control, Timelapse, Assistant App, CineStar',dailyRate:95000,status:'available',quantity:1}
  ]
};